import { useOAuthStore } from '@/store/oauth';

/**
 * Custom hook for managing OAuth connection states
 *
 */
export const useOAuth = () => {
  const {
    notionConnection,
    gitHubConnection,
    atlassianMCPConnection,
    figmaConnection,
    pagerDutyConnection,
    sentryConnection,
    newRelicConnection,
    dataDogConnection,
    grafanaConnection,
    cloudWatchConnection,
    userFilesConnection,
    setAtlassianMCPConnection,
    setNotionConnection,
    setGitHubConnection,
    setFigmaConnection,
    setPagerDutyConnection,
    setSentryConnection,
    setNewRelicConnection,
    setDataDogConnection,
    setGrafanaConnection,
    setCloudWatchConnection,
    setUserFilesConnection,
    resetConnections,
    resetNotionConnection,
    resetGitHubConnection,
    resetAtlassianMCPConnection,
    resetFigmaConnection,
    resetPagerDutyConnection,
    resetSentryConnection,
    resetNewRelicConnection,
    resetDataDogConnection,
    resetGrafanaConnection,
    resetCloudWatchConnection,
    resetUserFilesConnection,
  } = useOAuthStore();

  return {
    notionConnection,
    gitHubConnection,
    atlassianMCPConnection,
    figmaConnection,
    pagerDutyConnection,
    sentryConnection,
    newRelicConnection,
    dataDogConnection,
    grafanaConnection,
    cloudWatchConnection,
    setAtlassianMCPConnection,
    setNotionConnection,
    setGitHubConnection,
    setFigmaConnection,
    setPagerDutyConnection,
    setSentryConnection,
    setNewRelicConnection,
    setDataDogConnection,
    setGrafanaConnection,
    setCloudWatchConnection,
    resetConnections,
    resetNotionConnection,
    resetGitHubConnection,
    resetAtlassianMCPConnection,
    resetFigmaConnection,
    resetPagerDutyConnection,
    resetSentryConnection,
    resetNewRelicConnection,
    resetDataDogConnection,
    resetGrafanaConnection,
    resetCloudWatchConnection,
    userFilesConnection,
    setUserFilesConnection,
    resetUserFilesConnection,
  };
};
