"""llm_session_id_col

Revision ID: ed2aa9900293
Revises: 3dec9882922b
Create Date: 2025-08-12 11:22:04.384804

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed2aa9900293"
down_revision = "3dec9882922b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_agent_sessions", sa.Column("llm_session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_agent_sessions", "llm_session_id")
    # ### end Alembic commands ###
