"""add_agent_identifier

Revision ID: 56cd3116b5a8
Revises: a886752fd6b6
Create Date: 2025-08-20 20:53:16.469033

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "56cd3116b5a8"
down_revision = "a886752fd6b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE agentidentifier ADD VALUE 'REQUIREMENTS_TO_TICKETS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
