"""add code review in agent identifier

Revision ID: 9dbe7c4d62da
Revises: 7e1873cdacd9
Create Date: 2025-09-02 07:37:50.868639

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "9dbe7c4d62da"
down_revision = "7e1873cdacd9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE agentidentifier ADD VALUE 'CODE_REVIEWER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
